// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDz9Q87CyzpewJ5su_1XbRxyDU_rfjbwbU',
    appId: '1:1098995889120:web:e3b7df3684f5f5e1bcb185',
    messagingSenderId: '1098995889120',
    projectId: 'hapi-3abe6',
    authDomain: 'hapi-3abe6.firebaseapp.com',
    storageBucket: 'hapi-3abe6.appspot.com',
    measurementId: 'G-EBRCGLCVQ2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDuHP_FLd4xh4blsKWMWN0svLsZ5Nm3Jtc',
    appId: '1:1098995889120:android:97f3c01da90fb04fbcb185',
    messagingSenderId: '1098995889120',
    projectId: 'hapi-3abe6',
    storageBucket: 'hapi-3abe6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA9cvNBFroeZrR2S38w5CBTlGi8LjR4nmM',
    appId: '1:1098995889120:ios:7ce3ed2f24ecaca8bcb185',
    messagingSenderId: '1098995889120',
    projectId: 'hapi-3abe6',
    storageBucket: 'hapi-3abe6.appspot.com',
    iosClientId: '1098995889120-90nl38lof89knv11d44aof22rhb0jl38.apps.googleusercontent.com',
    iosBundleId: 'com.example.ddz',
  );
}
